# Generated by Django 5.0 on 2023-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweetogram", "0002_analytics_remove_post_header_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="last_token_refresh",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
